### ISSUE TITLE
Annex 1 indentation 

### ISSUE THREAD

**Issue by alice-dub** [MinhHaDuong/VN-Power-Scenario#21]
On my computer the script didn't differentiate the two last columns of the annex1.txt file. I changed the indentation of last column data.
https://github.com/alice-dub/VN-Power-Scenario/commit/b8186dd4d2bf3f2cbbc97053ecfd807200443bbe

**Comment by alice-dub** [comment]
Sorry for the imprecision:
I run the Run.py script with "summarize" argument (python Run.py "summarize")

The error raised is: 
AttributeError: 'DataFrameGroupBy' object has no attribute 'capacity_MW'

**Comment by MinhHaDuong** [comment]
Une fois que la colonne est bien alignée dans annex1.txt,
tu peux m'envoyer une pull request pour que j'intègre le fichier stp ?

**Comment by MinhHaDuong** [comment]
Attention la pull request ne doit couvrir que les modifications du fichier annex1.txt.
Ne remonte pas toute ta branche dans ton master, seulement le commit  b8186dd   et compagnie.

**Comment by MinhHaDuong** [comment]
J'avais demandé une colonne bien alignée. Bon on va dire que c'était un coup d'essai. J'ai intégré le commit  b8186dd  , accepté le  pull request, et aligné la collonne ( https://github.com/MinhHaDuong/VN-Power-Scenario/commit/23ff6f487e4b3f940083c352b951226423b27f1c )
